# our site configuration

title: mapquest!
baseurl: /mapquest/

# otherwise http://maxjacobson.github.io/mapquest/Gemfile would be included in the generated site
exclude:
- LICENSE
- README.md
- Gemfile
- Gemfile.lock
- Guardfile

